const words = [
    "guitarra", "elefante", "programa", "javascript", "tecnologia", "internet", "montaña", "bicicleta", "ciencia", "historia",
    "gato", "perro", "pelota", "espejo", "camara", "celular", "jardin", "familia", "espanol", "musica", "pelicula", "playa",
    "viaje", "avion", "planta", "fruta", "reloj", "libro", "arte", "pintura", "fotografia", "feliz", "triste", "sonrisa",
    "casa", "coche", "moto", "trabajo", "almohada", "elefante", "espejo", "astronomia", "galaxia", "biologia", "quimica",
    "fisica", "geografia", "matematicas", "historia", "literatura", "filosofia", "politica", "economia", "psicologia",
    "medicina", "deporte", "medalla", "teatro", "cine", "radio", "periodico", "revista", "telefono", "videojuego", "robot",
    "futuro", "energia", "reciclaje", "salud", "cocina", "receta", "moda", "diseño", "escultura", "religion", "meditacion",
    "solidaridad", "voluntario", "azucar", "cambiar", "enfoque", "azulejo", "abogado", "libertad", "cadena", "niebla", "carne",
    "delfin", "pasillo", "guitarra", "cadena", "lenguaje", "silla", "mochila", "tobillo", "papel", "espejo", "pastel", "azulejo",
    "noticia", "viaje", "elefante", "alumno", "ciudad", "montaña", "calendario", "circulo", "nube", "vuelo", "nadar", "buscar",
    "cuerda", "traje", "agujero", "abuelo", "relampago", "semilla", "cristal", "ocultar", "sombrero", "escuela", "saltar",
    "camino", "gigante", "solucion", "botella", "candado", "piloto", "muela", "fiesta", "palabra", "manzana", "sombra",
    "dulce", "pintor", "hueso", "helado", "joya", "viaje", "limon", "luz", "maquina", "gafas", "guante", "embarcar", "vela",
    "navegar", "oasis", "patria", "quitar", "rayo", "quitar", "sable", "sueño", "tobillo", "tesoro", "uvas", "viento", "zorro",
    "hilo", "sabor", "viaje", "flecha", "volar", "amigo", "fuego", "candela", "señal", "silencio", "peluche", "fantasma",
    "mariposa", "flores", "frutas", "invierno", "sombrero", "rana", "jugador", "cama", "cofre", "risa", "esfera", "cubo",
    "piedra", "piso", "torre", "espejo", "cable", "madera", "escoba", "bailar", "cosecha", "abeja", "espejo", "luz", "trono",
    "princesa", "muralla", "rana", "cruz", "crucero", "manzana", "estrella", "zorro", "oso", "leopardo", "tigre", "león", "serpiente",
    "tortuga", "rana", "aguila", "pajaro", "gaviota", "vaca", "caballo", "tigre", "leon", "oso", "delfin", "ballena", "medusa", "pez",
    "camello", "elefante", "rinoceronte", "hipopotamo", "cocodrilo", "jirafa", "canguro", "koala", "pinguino", "ardilla", "ciervo",
    "conejo", "oso polar", "mapache", "zorro", "murcielago", "araña", "escarabajo", "mariposa", "abeja", "mosquito", "hormiga",
    "grillo", "saltamontes", "ciempies", "libelula", "cucaracha", "escorpion", "serpiente", "lagartija", "tortuga", "cocodrilo",
    "camaleon", "lagarto", "tucan", "loro", "cuervo", "colibri", "buitre", "halcon", "aguila", "gavilan", "búho", "lechuza", "cisne",
    "pato", "ganso", "pelícano", "flamenco", "garza", "cigüeña", "avestruz", "pavo", "pollo", "gallo", "gallina", "cabra", "oveja",
    "vaca", "toro", "cerdo", "jabali", "perro", "gato", "conejo", "raton", "hurón", "hamster", "cobaya", "conejo", "mapache", "comadreja",
    "armadillo", "osos polares", "hiena", "zorro", "leon", "tigre", "jaguar", "pantera", "leopardo", "guepardo", "elefante", "rinoceronte",
    "hipopotamo", "jirafa", "cocodrilo", "caiman", "serpiente", "tortuga", "tortuga", "tortuga marina", "tiburón", "pez payaso", "delfín",
    "ballena", "orca", "tigre blanco", "leon blanco", "oso polar", "panda", "koala", "canguro", "walabi", "kiwi", "emu", "pingüino",
    "perezoso"
];